# My conf test
baudrate = 115200
temperture_threshold = 60.5
device_id = luanqibazao   
uart_dev = "/dev/ttyAMA0"
log_file = /home/sandocean/edge-sentinel/rpi_app/build/test.log
database_file = /home/sandocean/edge-sentinel/rpi_app/database/gateway.db
ip = 127.0.0.1
port = 8080